title: Priyank Shelat
# logo: /assets/img/logo.png
description: Hello, I am a new graduate looking for opportunities to learn and grow.
  My current interests include computer vision and image analytics as well as scientific simulation (recent development).
  Hopefully, some of my projects in this portfolio will help show my ability and drive.
  <br><br>
  I also have a variety of other interests, such as investing and trading, sports, and a bunch more.
  I love learning about and discussing new ideas. You could say that talking is a hobby so feel free to reach out to me for anything.
  <br><br>
  <a href="https://www.linkedin.com/in/priyank-s-2a94118a/">View My LinkedIn Profile</a><br>
  <a href="https://priyank-personal-webpage.herokuapp.com/index.html">And My "Website"</a>
google_analytics:
theme: jekyll-theme-minimal
