title: Priyank Shelat
# logo: /assets/img/logo.png
description: Hello, I am a new grad looking for opportunities to learn and grow. I aspire to be a full stack data scientist, if there is such a thing.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
